import { mkdtempSync } from "node:fs";import { tmpdir } from "node:os";import { join } from "node:path";import { describe,expect,it } from "vitest";import { CaptureWorker } from "./capture-worker.js";import { GatewayStore } from "./gateway-store.js";
describe("CaptureWorker",()=>{it("retries Core and Skill independently",async()=>{const store=new GatewayStore(join(mkdtempSync(join(tmpdir(),"worker-test-")),"db.sqlite"));const context=store.openContext({id:"p",userId:"u"},{teamId:"t",userId:"u",agentId:"a"},{host:"codex",sessionId:"s",workspace:"/repo"},60000);store.beginTurn(context.contextId,"turn","hello");store.enqueueCapture(context.contextId,"turn","world");let skillAttempts=0;const fetcher=async(input:URL|RequestInfo)=>{const path=String(input);if(path.endsWith("/v3/skill/conversation/add")&&skillAttempts++===0)return response(500,{code:500,message:"retry"});return response(200,{code:0,data:{accepted:true}})};const original=globalThis.fetch;globalThis.fetch=fetcher as typeof fetch;try{const worker=new CaptureWorker(store,{baseUrl:"http://core",serviceId:"svc",timeoutMs:1000});await worker.drain();expect(store.pendingCaptureCount()).toBe(1);await new Promise((resolve)=>setTimeout(resolve,2100));await worker.drain();expect(store.pendingCaptureCount()).toBe(0)}finally{globalThis.fetch=original}})});
describe("CaptureWorker direct skill extraction",()=>{
  it("submits a tool-backed SessionEnd transcript through the direct extract API",async()=>{const store=new GatewayStore(join(mkdtempSync(join(tmpdir(),"extract-worker-test-")),"db.sqlite"));const context=store.openContext({id:"p",userId:"u"},{teamId:"t",userId:"u",agentId:"a"},{host:"codex",sessionId:"s",workspace:"/repo"},60000);store.beginTurn(context.contextId,"turn","implement reusable validation");store.recordToolUse(context.contextId,"turn","tool-1","Bash",{command:"test"},{result:"passed"});store.recordToolUse(context.contextId,"turn","tool-2","apply_patch",{patch:"validator"},{result:"updated"});store.enqueueCapture(context.contextId,"turn","Implemented and tested the reusable validator.");store.enqueueSkillExtraction(context.contextId,"session complete");let extractBody:Record<string,unknown>|undefined;const fetcher=async(input:URL|RequestInfo,init?:RequestInit)=>{const path=String(input);if(path.endsWith("/v3/skill/extract")){extractBody=JSON.parse(String(init?.body));return response(200,{code:0,data:{ok:true,task_id:"skill-task-1"}})}return response(200,{code:0,data:{accepted:true}})};const original=globalThis.fetch;globalThis.fetch=fetcher as typeof fetch;try{const worker=new CaptureWorker(store,{baseUrl:"http://core",serviceId:"svc",timeoutMs:1000});await worker.drain();expect(extractBody).toMatchObject({session_id:"s"});expect(String(extractBody?.reason)).toContain("repeatable workflow");expect(store.pendingSkillExtractionCount()).toBe(0);expect(store.latestSkillExtraction(context.contextId)).toMatchObject({status:"submitted",taskId:"skill-task-1"})}finally{globalThis.fetch=original}});
  it("skips a trivial session instead of spending a Skill LLM call",async()=>{const store=new GatewayStore(join(mkdtempSync(join(tmpdir(),"extract-skip-test-")),"db.sqlite"));const context=store.openContext({id:"p",userId:"u"},{teamId:"t",userId:"u",agentId:"a"},{host:"codex",sessionId:"s",workspace:"/repo"},60000);store.beginTurn(context.contextId,"turn","list skills");store.enqueueCapture(context.contextId,"turn","two skills");store.enqueueSkillExtraction(context.contextId,"done");const original=globalThis.fetch;let calls=0;globalThis.fetch=(async()=>{calls++;return response(200,{code:0,data:{}})}) as typeof fetch;try{await new CaptureWorker(store,{baseUrl:"http://core",serviceId:"svc",timeoutMs:1000}).drain();expect(calls).toBe(2);expect(store.latestSkillExtraction(context.contextId)).toMatchObject({status:"skipped"})}finally{globalThis.fetch=original}});
  it("skips a SessionEnd event when no completed conversation was captured",async()=>{const store=new GatewayStore(join(mkdtempSync(join(tmpdir(),"extract-empty-test-")),"db.sqlite"));const context=store.openContext({id:"p",userId:"u"},{teamId:"t",userId:"u",agentId:"a"},{host:"codex",sessionId:"s",workspace:"/repo"},60000);store.enqueueSkillExtraction(context.contextId,"session complete");const original=globalThis.fetch;let calls=0;globalThis.fetch=(async()=>{calls++;return response(200,{code:0,data:{}})}) as typeof fetch;try{await new CaptureWorker(store,{baseUrl:"http://core",serviceId:"svc",timeoutMs:1000},1,1).drain();expect(calls).toBe(0);expect(store.pendingSkillExtractionCount()).toBe(0);expect(store.deadSkillExtractionCount()).toBe(0);expect(store.latestSkillExtraction(context.contextId)).toMatchObject({status:"skipped",lastError:"no completed conversation was captured"})}finally{globalThis.fetch=original}});
});
describe("CaptureWorker terminal failures",()=>{
  it("moves exhausted sinks to dead letter instead of retrying forever",async()=>{const store=new GatewayStore(join(mkdtempSync(join(tmpdir(),"worker-dead-test-")),"db.sqlite"));const context=store.openContext({id:"p",userId:"u"},{teamId:"t",userId:"u",agentId:"a"},{host:"codex",sessionId:"s",workspace:"/repo"},60000);store.beginTurn(context.contextId,"turn","persist this decision");store.enqueueCapture(context.contextId,"turn","done");const original=globalThis.fetch;globalThis.fetch=(async()=>response(503,{code:503,message:"unavailable"})) as typeof fetch;try{await new CaptureWorker(store,{baseUrl:"http://core",serviceId:"svc",timeoutMs:1000},2,1).drain();expect(store.pendingCaptureCount()).toBe(0);expect(store.deadCaptureCount()).toBe(1)}finally{globalThis.fetch=original}});
});
function response(status:number,body:unknown){return Promise.resolve(new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json"}}))}
