import { describe,expect,it,vi } from "vitest";import { CoreClient,CoreDirectoryClient } from "./core-client.js";
describe("CoreDirectoryClient",()=>{
  it("paginates metadata at the native limit",async()=>{const offsets:number[]=[];const fetcher=vi.fn(async(_input:URL|RequestInfo,init?:RequestInit)=>{const body=JSON.parse(String(init?.body));offsets.push(body.offset);const items=body.offset===0?Array.from({length:100},(_,i)=>({id:i})): [{id:100}];return new Response(JSON.stringify({code:0,data:{items,total:101}}),{status:200,headers:{"Content-Type":"application/json"}})});const client=new CoreDirectoryClient({baseUrl:"http://core",serviceId:"svc",timeoutMs:1000},fetcher as typeof fetch);const result=await client.options({id:"p",userId:"u",userKey:"uk"}) as {teams:unknown[];agents:unknown[]};expect(result.teams).toHaveLength(101);expect(result.agents).toHaveLength(101);expect(offsets.sort((a,b)=>a-b)).toEqual([0,0,100,100])});
  it("verifies a page API key through the public metadata auth route",async()=>{const fetcher=vi.fn(async(input:URL|RequestInfo,init?:RequestInit)=>{expect(String(input)).toBe("http://core/v3/meta/auth/verify");expect(JSON.parse(String(init?.body))).toEqual({user_key:"page-key"});expect(new Headers(init?.headers).get("authorization")).toBe("Bearer service-key");return new Response(JSON.stringify({code:0,data:{valid:true,user:{user_id:"usr-1"}}}),{status:200})});const client=new CoreDirectoryClient({baseUrl:"http://core",serviceId:"svc",token:"service-key",timeoutMs:1000},fetcher as typeof fetch);await expect(client.verifyUserKey("page-key")).resolves.toBe("usr-1")});
  it("returns null for an invalid page API key",async()=>{const fetcher=vi.fn(async()=>new Response(JSON.stringify({code:0,data:{valid:false,user:null}}),{status:200}));const client=new CoreDirectoryClient({baseUrl:"http://core",serviceId:"svc",timeoutMs:1000},fetcher as typeof fetch);await expect(client.verifyUserKey("bad")).resolves.toBeNull()});
  it("returns only active agents owned by the authenticated principal",async()=>{const fetcher=vi.fn(async()=>new Response(JSON.stringify({code:0,data:{items:[{agent_id:"a1",team_id:"t1",owner_user_id:"u1",name:"A",status:"active"},{agent_id:"a2",team_id:"t1",owner_user_id:"u1",name:"B",status:"archived"},{agent_id:"a3",team_id:"t2",owner_user_id:"u2",name:"C",status:"active"}],total:3}}),{status:200}));const client=new CoreDirectoryClient({baseUrl:"http://core",serviceId:"svc",timeoutMs:1000},fetcher as typeof fetch);await expect(client.listOwnedActiveAgents({id:"p",userId:"u1",userKey:"uk"})).resolves.toMatchObject([{agent_id:"a1",team_id:"t1"}])});
});

describe("CoreClient recall timeout",()=>{it("uses the recall override instead of the longer worker timeout",async()=>{const fetcher=vi.fn(async(_input:URL|RequestInfo,init?:RequestInit)=>await new Promise<Response>((_resolve,reject)=>{init?.signal?.addEventListener("abort",()=>reject(init.signal?.reason),{once:true})}));const client=new CoreClient({baseUrl:"http://core",serviceId:"svc",timeoutMs:5000},{teamId:"t",userId:"u",agentId:"a",sessionId:"s"},fetcher as typeof fetch);const started=Date.now();await expect(client.searchMemory("query",5,undefined,40)).rejects.toThrow();expect(Date.now()-started).toBeLessThan(500)})});

describe("CoreClient capture idempotency",()=>{
  it("sends the durable event id and stable message time to Core",async()=>{let body:Record<string,unknown>|undefined;const fetcher=vi.fn(async(_input:URL|RequestInfo,init?:RequestInit)=>{body=JSON.parse(String(init?.body));return new Response(JSON.stringify({code:0,data:{accepted_ids:["m1","m2"]}}),{status:200,headers:{"Content-Type":"application/json"}})});const client=new CoreClient({baseUrl:"http://core",serviceId:"svc",timeoutMs:5000},{teamId:"t",userId:"u",agentId:"a",sessionId:"s"},fetcher as typeof fetch);await client.addConversation([{role:"user",content:"hello",recorded_at:"2026-09-03T10:00:00.000Z"},{role:"assistant",content:"world",recorded_at:"2026-09-03T10:00:00.001Z"}],"event-1234567890abcdef",30_000);expect(body).toMatchObject({session_id:"s",idempotency_key:"event-1234567890abcdef",messages:[{recorded_at:"2026-09-03T10:00:00.000Z"},{recorded_at:"2026-09-03T10:00:00.001Z"}]})});
  it("uses the capture-specific timeout",async()=>{const fetcher=vi.fn(async(_input:URL|RequestInfo,init?:RequestInit)=>await new Promise<Response>((_resolve,reject)=>{init?.signal?.addEventListener("abort",()=>reject(init.signal?.reason),{once:true})}));const client=new CoreClient({baseUrl:"http://core",serviceId:"svc",timeoutMs:5000},{teamId:"t",userId:"u",agentId:"a",sessionId:"s"},fetcher as typeof fetch);const started=Date.now();await expect(client.addConversation([{role:"user",content:"hello"}],"event-1234567890abcdef",40)).rejects.toThrow();expect(Date.now()-started).toBeLessThan(500)});
});

describe("CoreClient knowledge scope",()=>{it("intersects fixed Agent bindings with readable assets and normalizes Core entities as ready",async()=>{const fetcher=vi.fn(async(input:URL|RequestInfo,init?:RequestInit)=>{const url=String(input),body=JSON.parse(String(init?.body));let data:unknown;if(url.endsWith("/agent-fixed-asset/list-with-detail"))data={items:[{asset_id:"wiki-1",asset_type:"llm_wiki"},{asset_id:"wiki-denied",asset_type:"llm_wiki"},{asset_id:"cg-1",asset_type:"code_graph"}]};else if(url.endsWith("/asset/list-accessible"))data={items:[{asset_id:"wiki-1"},{asset_id:"cg-1"}],total:2};else{expect(url).toMatch(/\/knowledge\/list$/);expect(body.knowledge_ids.sort()).toEqual(["cg-1","wiki-1"]);data={items:[{knowledge_id:"wiki-1",type:"wiki",name:"Wiki"},{knowledge_id:"cg-1",type:"code-graph",name:"Code",status:"indexing"}]};}return new Response(JSON.stringify({code:0,data}),{status:200})});const client=new CoreClient({baseUrl:"http://core",serviceId:"svc",timeoutMs:1000},{teamId:"t",userId:"u",agentId:"a",sessionId:"s",userKey:"key"},fetcher as typeof fetch);await expect(client.listBoundKnowledge([])).resolves.toMatchObject([{knowledge_id:"wiki-1",status:"ready"},{knowledge_id:"cg-1",status:"indexing"}]);expect(fetcher).toHaveBeenCalledTimes(3)});});
